version: '2.28'

services:
  db:
    container_name: pg_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  order-service:
    build:
      context: .
      dockerfile: ../services/order-service/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@pg_db:5432/orders
    command: >
      sh -c "npx prisma migrate deploy &&
             npm start"
  # order-service:
  #   container_name: order-service 
  #   build: ../services/order-service
  #   depends_on:
  #     - pg_db
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - type: bind
  #       source: ../services/order-service
  #       target: /app
  #   env_file:
  #     - ../services/order-service/.env
  #   command: sh -c "npx prisma migrate deploy && npm start"

  migrate:
    container_name: prisma-migrate
    image: node:16
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sh", "-c", "npx prisma migrate dev --name init"]

